// Angular_DotNet/ClientApp/src/app/components/upload/upload.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, takeUntil } from 'rxjs';
import { DocumentService, NotificationService } from '../../core/services';
import { Document, SummarizeResponse, SummaryType, SUMMARY_TYPES } from '../../core/models';
import { FileSizePipe } from '../../shared/pipes';

/**
 * Upload Component
 * Handles document upload and AI summarization
 */
@Component({
  selector: 'app-upload',
  standalone: true,
  imports: [CommonModule, FormsModule, FileSizePipe],
  templateUrl: './upload.component.html',
  styleUrl: './upload.component.scss'
})
export class UploadComponent implements OnInit, OnDestroy {
  // State
  selectedFiles: File[] = [];
  uploadedDocs: Document[] = [];
  isUploading = false;
  message = '';
  messageType: 'success' | 'error' | '' = '';

  // AI Summary feature
  readonly summaryTypes = SUMMARY_TYPES;
  selectedSummaryType: SummaryType = 'general';
  isSummarizing: Record<string, boolean> = {};
  summaryResults: Record<string, SummarizeResponse> = {};

  // Cleanup
  private destroy$ = new Subject<void>();

  constructor(
    private documentService: DocumentService,
    private notificationService: NotificationService
  ) {}

  ngOnInit(): void {
    this.loadDocuments();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  /**
   * Load existing documents
   */
  loadDocuments(): void {
    this.documentService.getAll()
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response) => {
          if (response.success) {
            this.uploadedDocs = response.documents;
          }
        },
        error: (err) => console.error('Error loading documents:', err)
      });
  }

  /**
   * Handle file selection
   */
  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files) {
      this.selectedFiles = Array.from(input.files);
    }
  }

  /**
   * Handle drag over
   */
  onDragOver(event: DragEvent): void {
    event.preventDefault();
    event.stopPropagation();
  }

  /**
   * Handle file drop
   */
  onDrop(event: DragEvent): void {
    event.preventDefault();
    event.stopPropagation();
    if (event.dataTransfer?.files) {
      this.selectedFiles = Array.from(event.dataTransfer.files);
    }
  }

  /**
   * Upload selected files
   */
  upload(): void {
    if (this.selectedFiles.length === 0) {
      this.showMessage('กรุณาเลือกไฟล์ก่อน', 'error');
      return;
    }

    this.isUploading = true;
    this.message = '';

    this.documentService.upload(this.selectedFiles)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response) => {
          this.isUploading = false;
          if (response.success) {
            this.uploadedDocs = [...this.uploadedDocs, ...response.documents];
            this.showMessage(`อัพโหลดสำเร็จ ${response.documents.length} ไฟล์`, 'success');
            this.notificationService.success(`อัพโหลดสำเร็จ ${response.documents.length} ไฟล์`);
            this.selectedFiles = [];
          }
          if (response.errors?.length) {
            this.showMessage(`บางไฟล์อัพโหลดไม่สำเร็จ: ${response.errors.join(', ')}`, 'error');
          }
        },
        error: (err) => {
          this.isUploading = false;
          this.showMessage('เกิดข้อผิดพลาด: ' + err.message, 'error');
        }
      });
  }

  /**
   * Summarize document using AI
   */
  summarizeDocument(doc: Document): void {
    this.isSummarizing[doc.id] = true;
    
    this.documentService.summarize(doc.id, this.selectedSummaryType)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response) => {
          this.isSummarizing[doc.id] = false;
          if (response.success) {
            this.summaryResults[doc.id] = response;
            this.showMessage('สรุปเอกสารสำเร็จ!', 'success');
            this.notificationService.success('สรุปเอกสารสำเร็จ!');
          }
        },
        error: (err) => {
          this.isSummarizing[doc.id] = false;
          this.showMessage('เกิดข้อผิดพลาดในการสรุป: ' + err.message, 'error');
        }
      });
  }

  /**
   * Delete a document
   */
  deleteDocument(doc: Document): void {
    if (!confirm(`คุณต้องการลบเอกสาร "${doc.fileName}" หรือไม่?`)) {
      return;
    }

    this.documentService.delete(doc.id)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response) => {
          if (response.success) {
            this.uploadedDocs = this.uploadedDocs.filter(d => d.id !== doc.id);
            delete this.summaryResults[doc.id];
            this.showMessage('ลบเอกสารสำเร็จ', 'success');
            this.notificationService.success('ลบเอกสารสำเร็จ');
          }
        },
        error: (err) => {
          this.showMessage('เกิดข้อผิดพลาดในการลบ: ' + err.message, 'error');
        }
      });
  }

  /**
   * Clear summary result
   */
  clearSummary(docId: string): void {
    delete this.summaryResults[docId];
  }

  /**
   * Get summary type label
   */
  getSummaryTypeLabel(type: string): string {
    const found = this.summaryTypes.find(t => t.value === type);
    return found ? found.label : type;
  }

  /**
   * Remove file from selection
   */
  removeFile(index: number): void {
    this.selectedFiles.splice(index, 1);
  }

  /**
   * Track documents by id
   */
  trackByDocId(index: number, doc: Document): string {
    return doc.id;
  }

  /**
   * Show message
   */
  private showMessage(msg: string, type: 'success' | 'error'): void {
    this.message = msg;
    this.messageType = type;
    setTimeout(() => {
      this.message = '';
      this.messageType = '';
    }, 5000);
  }
}

<div class="upload-container">
  <h2>📄 อัพโหลดและวิเคราะห์เอกสาร</h2>
  
  <div class="drop-zone" 
       (dragover)="onDragOver($event)" 
       (drop)="onDrop($event)"
       [class.has-files]="selectedFiles.length > 0">
    <div class="drop-content">
      <span class="icon">📄</span>
      <p>ลากไฟล์มาวางที่นี่ หรือ</p>
      <label class="file-input-label">
        เลือกไฟล์
        <input type="file" multiple (change)="onFileSelected($event)" accept=".txt,.md,.json,.csv,.pdf,.doc,.docx">
      </label>
      <small>รองรับไฟล์ .txt, .md, .json, .csv, .pdf, .doc, .docx</small>
    </div>
  </div>

  @if (selectedFiles.length > 0) {
    <div class="selected-files">
      <h4>ไฟล์ที่เลือก ({{ selectedFiles.length }} ไฟล์)</h4>
      <ul>
        @for (file of selectedFiles; track file.name; let i = $index) {
          <li>
            <span class="file-name">{{ file.name }}</span>
            <span class="file-size">{{ file.size | fileSize }}</span>
            <button class="remove-btn" (click)="removeFile(i)">✕</button>
          </li>
        }
      </ul>
    </div>
  }

  <button class="upload-btn" 
          (click)="upload()" 
          [disabled]="isUploading || selectedFiles.length === 0">
    @if (isUploading) {
      <span class="spinner"></span> กำลังอัพโหลด...
    } @else {
      อัพโหลดเอกสาร
    }
  </button>

  @if (message) {
    <div class="message" [class.success]="messageType === 'success'" [class.error]="messageType === 'error'">
      {{ message }}
    </div>
  }

  @if (uploadedDocs.length > 0) {
    <div class="uploaded-section">
      <h3>📚 เอกสารที่อัพโหลด</h3>
      
      <!-- Summary Type Selector -->
      <div class="summary-options">
        <label>เลือกรูปแบบการสรุป:</label>
        <select [(ngModel)]="selectedSummaryType">
          @for (type of summaryTypes; track type.value) {
            <option [value]="type.value">{{ type.icon }} {{ type.label }}</option>
          }
        </select>
      </div>

      <div class="documents-grid">
        @for (doc of uploadedDocs; track trackByDocId) {
          <div class="document-card">
            <div class="doc-header">
              <span class="doc-icon">📄</span>
              <div class="doc-info">
                <h4>{{ doc.title || doc.fileName }}</h4>
                <small>{{ doc.fileName }} • {{ doc.size | fileSize }}</small>
              </div>
              <button class="delete-btn" (click)="deleteDocument(doc)" title="ลบเอกสาร">🗑️</button>
            </div>

            <div class="doc-actions">
              <button class="summarize-btn" 
                      (click)="summarizeDocument(doc)" 
                      [disabled]="isSummarizing[doc.id]">
                @if (isSummarizing[doc.id]) {
                  <span class="spinner"></span> กำลังสรุป...
                } @else {
                  🤖 สรุปด้วย AI
                }
              </button>
            </div>

            @if (summaryResults[doc.id]) {
              <div class="summary-result">
                <div class="summary-header">
                  <h5>✨ {{ getSummaryTypeLabel(summaryResults[doc.id].summaryType) }}</h5>
                  <button class="close-summary" (click)="clearSummary(doc.id)">✕</button>
                </div>
                <div class="summary-content">
                  {{ summaryResults[doc.id].summary }}
                </div>
              </div>
            }
          </div>
        }
      </div>
    </div>
  }
</div>

// NodeJs_NextJs/src/app/upload/page.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import { Document, SummarizeResponse, SUMMARY_TYPES, SummaryType } from '@/types';

export default function UploadPage() {
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const [uploadedDocs, setUploadedDocs] = useState<Document[]>([]);
  const [isUploading, setIsUploading] = useState(false);
  const [message, setMessage] = useState('');
  const [messageType, setMessageType] = useState<'success' | 'error' | ''>('');
  
  // AI Summary feature
  const [selectedSummaryType, setSelectedSummaryType] = useState<SummaryType>('general');
  const [isSummarizing, setIsSummarizing] = useState<Record<string, boolean>>({});
  const [summaryResults, setSummaryResults] = useState<Record<string, SummarizeResponse>>({});

  const showMessage = useCallback((msg: string, type: 'success' | 'error') => {
    setMessage(msg);
    setMessageType(type);
    setTimeout(() => {
      setMessage('');
      setMessageType('');
    }, 5000);
  }, []);

  const loadDocuments = useCallback(async () => {
    try {
      const response = await fetch('/api/upload');
      const data = await response.json();
      if (data.success) {
        setUploadedDocs(data.documents);
      }
    } catch (err) {
      console.error('Error loading documents:', err);
    }
  }, []);

  useEffect(() => {
    loadDocuments();
  }, [loadDocuments]);

  const formatFileSize = (bytes: number) => {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setSelectedFiles(Array.from(e.target.files));
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.dataTransfer.files) {
      setSelectedFiles(Array.from(e.dataTransfer.files));
    }
  };

  const handleUpload = async () => {
    if (selectedFiles.length === 0) {
      showMessage('กรุณาเลือกไฟล์ก่อน', 'error');
      return;
    }

    setIsUploading(true);

    try {
      const formData = new FormData();
      selectedFiles.forEach(file => {
        formData.append('files', file);
      });

      const response = await fetch('/api/upload', {
        method: 'POST',
        body: formData,
      });

      const data = await response.json();

      if (data.success) {
        setUploadedDocs([...uploadedDocs, ...data.documents]);
        showMessage(`อัพโหลดสำเร็จ ${data.documents.length} ไฟล์`, 'success');
        setSelectedFiles([]);
      }

      if (data.errors?.length) {
        showMessage(`บางไฟล์อัพโหลดไม่สำเร็จ: ${data.errors.join(', ')}`, 'error');
      }
    } catch (err) {
      showMessage('เกิดข้อผิดพลาด: ' + (err instanceof Error ? err.message : 'Unknown error'), 'error');
    } finally {
      setIsUploading(false);
    }
  };

  const handleSummarize = async (doc: Document) => {
    setIsSummarizing({ ...isSummarizing, [doc.id]: true });

    try {
      const response = await fetch(`/api/upload/summarize/${doc.id}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ summaryType: selectedSummaryType }),
      });

      const data = await response.json();

      if (data.success) {
        setSummaryResults({ ...summaryResults, [doc.id]: data });
        showMessage('สรุปเอกสารสำเร็จ!', 'success');
      } else {
        showMessage('เกิดข้อผิดพลาดในการสรุป', 'error');
      }
    } catch (err) {
      showMessage('เกิดข้อผิดพลาด: ' + (err instanceof Error ? err.message : 'Unknown error'), 'error');
    } finally {
      setIsSummarizing({ ...isSummarizing, [doc.id]: false });
    }
  };

  const handleDelete = async (doc: Document) => {
    if (!confirm(`คุณต้องการลบเอกสาร "${doc.fileName}" หรือไม่?`)) {
      return;
    }

    try {
      const response = await fetch(`/api/upload/documents/${doc.id}`, {
        method: 'DELETE',
      });

      const data = await response.json();

      if (data.success) {
        setUploadedDocs(uploadedDocs.filter(d => d.id !== doc.id));
        const newSummaryResults = { ...summaryResults };
        delete newSummaryResults[doc.id];
        setSummaryResults(newSummaryResults);
        showMessage('ลบเอกสารสำเร็จ', 'success');
      }
    } catch (err) {
      showMessage('เกิดข้อผิดพลาด: ' + (err instanceof Error ? err.message : 'Unknown error'), 'error');
    }
  };

  const removeFile = (index: number) => {
    const newFiles = [...selectedFiles];
    newFiles.splice(index, 1);
    setSelectedFiles(newFiles);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-fadeIn">
      {/* Header */}
      <div className="text-center">
        <h1 className="text-3xl font-bold text-gray-800 mb-2">📤 อัพโหลดเอกสาร</h1>
        <p className="text-gray-600">อัพโหลดเอกสารและใช้ AI สรุปเนื้อหา</p>
      </div>

      {/* Message */}
      {message && (
        <div
          className={`p-4 rounded-lg ${
            messageType === 'success'
              ? 'bg-green-100 text-green-800 border border-green-200'
              : 'bg-red-100 text-red-800 border border-red-200'
          }`}
        >
          {message}
        </div>
      )}

      {/* Upload Area */}
      <div className="card">
        <div
          className="border-2 border-dashed border-gray-300 rounded-xl p-8 text-center hover:border-primary-500 transition-colors cursor-pointer"
          onDragOver={handleDragOver}
          onDrop={handleDrop}
          onClick={() => document.getElementById('fileInput')?.click()}
        >
          <div className="text-5xl mb-4">📁</div>
          <p className="text-gray-600 mb-2">ลากไฟล์มาวางที่นี่ หรือคลิกเพื่อเลือกไฟล์</p>
          <p className="text-sm text-gray-400">รองรับไฟล์ .txt, .md, .pdf, .docx (สูงสุด 50MB)</p>
          <input
            id="fileInput"
            type="file"
            multiple
            className="hidden"
            onChange={handleFileSelect}
            accept=".txt,.md,.pdf,.docx,.doc"
          />
        </div>

        {/* Selected Files */}
        {selectedFiles.length > 0 && (
          <div className="mt-6">
            <h3 className="font-semibold mb-3">📎 ไฟล์ที่เลือก ({selectedFiles.length})</h3>
            <div className="space-y-2">
              {selectedFiles.map((file, index) => (
                <div
                  key={index}
                  className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">📄</span>
                    <div>
                      <p className="font-medium text-gray-800">{file.name}</p>
                      <p className="text-sm text-gray-500">{formatFileSize(file.size)}</p>
                    </div>
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      removeFile(index);
                    }}
                    className="text-red-500 hover:text-red-700 p-2"
                  >
                    ✕
                  </button>
                </div>
              ))}
            </div>

            <button
              onClick={handleUpload}
              disabled={isUploading}
              className="mt-4 btn btn-primary w-full flex items-center justify-center gap-2"
            >
              {isUploading ? (
                <>
                  <div className="spinner w-5 h-5"></div>
                  กำลังอัพโหลด...
                </>
              ) : (
                <>
                  📤 อัพโหลดไฟล์
                </>
              )}
            </button>
          </div>
        )}
      </div>

      {/* Summary Type Selection */}
      <div className="card">
        <h3 className="font-semibold mb-4">🤖 ประเภทการสรุป AI</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {SUMMARY_TYPES.map((type) => (
            <button
              key={type.value}
              onClick={() => setSelectedSummaryType(type.value)}
              className={`p-3 rounded-lg border-2 transition-all ${
                selectedSummaryType === type.value
                  ? 'border-primary-500 bg-primary-50'
                  : 'border-gray-200 hover:border-gray-300'
              }`}
            >
              <p className="font-medium">{type.label}</p>
              <p className="text-xs text-gray-500">{type.description}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Uploaded Documents */}
      {uploadedDocs.length > 0 && (
        <div className="card">
          <h3 className="font-semibold mb-4">📚 เอกสารที่อัพโหลด ({uploadedDocs.length})</h3>
          <div className="space-y-4">
            {uploadedDocs.map((doc) => (
              <div key={doc.id} className="border rounded-xl p-4">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <span className="text-3xl">📄</span>
                    <div>
                      <p className="font-semibold text-gray-800">{doc.title}</p>
                      <p className="text-sm text-gray-500">
                        {doc.fileName} • {formatFileSize(doc.size)} •{' '}
                        {new Date(doc.uploadedAt).toLocaleString('th-TH')}
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => handleSummarize(doc)}
                      disabled={isSummarizing[doc.id]}
                      className="btn btn-primary text-sm"
                    >
                      {isSummarizing[doc.id] ? (
                        <>
                          <span className="spinner w-4 h-4 mr-1"></span>
                          กำลังสรุป...
                        </>
                      ) : (
                        '🤖 สรุปด้วย AI'
                      )}
                    </button>
                    <button
                      onClick={() => handleDelete(doc)}
                      className="btn btn-danger text-sm"
                    >
                      🗑️ ลบ
                    </button>
                  </div>
                </div>

                {/* Summary Result */}
                {summaryResults[doc.id] && (
                  <div className="mt-4 p-4 bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg border border-blue-100">
                    <div className="flex justify-between items-center mb-2">
                      <h4 className="font-semibold text-primary-700">
                        ✨ ผลการสรุป ({summaryResults[doc.id].summaryType})
                      </h4>
                      <button
                        onClick={() => {
                          const newResults = { ...summaryResults };
                          delete newResults[doc.id];
                          setSummaryResults(newResults);
                        }}
                        className="text-gray-400 hover:text-gray-600"
                      >
                        ✕
                      </button>
                    </div>
                    <div className="prose prose-sm max-w-none">
                      <div className="whitespace-pre-wrap text-gray-700">
                        {summaryResults[doc.id].summary}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Empty State */}
      {uploadedDocs.length === 0 && (
        <div className="card text-center py-12">
          <div className="text-6xl mb-4">📭</div>
          <h3 className="text-xl font-semibold text-gray-700 mb-2">ยังไม่มีเอกสาร</h3>
          <p className="text-gray-500">เริ่มต้นอัพโหลดเอกสารเพื่อใช้งานฟีเจอร์ AI สรุปเนื้อหา</p>
        </div>
      )}
    </div>
  );
}
