// NodeJs_NextJs/src/components/ChatWidget.tsx
'use client';

import { useState, useRef, useEffect } from 'react';
import { ChatMessage } from '@/types';

export default function ChatWidget() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [userInput, setUserInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [unreadCount, setUnreadCount] = useState(0);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const toggleChat = () => {
    setIsOpen(!isOpen);
    if (!isOpen) {
      setUnreadCount(0);
    }
  };

  const addMessage = (message: ChatMessage) => {
    setMessages(prev => [...prev, message]);
  };

  const sendMessage = async (messageText?: string) => {
    const question = (messageText || userInput).trim();
    if (!question || isLoading) return;

    // Add user message
    addMessage({
      role: 'user',
      content: question,
      timestamp: new Date(),
    });

    setUserInput('');
    setIsLoading(true);

    try {
      const response = await fetch('/api/chat/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question }),
      });

      const data = await response.json();

      const content = data.success
        ? data.answer
        : `เกิดข้อผิดพลาด: ${data.error || 'Unknown error'}`;

      addMessage({
        role: 'assistant',
        content,
        timestamp: new Date(),
      });

      if (!isOpen) {
        setUnreadCount(prev => prev + 1);
      }
    } catch (err) {
      addMessage({
        role: 'assistant',
        content: `เกิดข้อผิดพลาด: ${err instanceof Error ? err.message : 'Unknown error'}`,
        timestamp: new Date(),
      });
    } finally {
      setIsLoading(false);
    }
  };

  const sendQuickMessage = (message: string) => {
    sendMessage(message);
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const clearChat = () => {
    setMessages([]);
  };

  const quickActions = [
    { icon: '💱', label: 'อัตราแลกเปลี่ยนวันนี้', query: 'อัตราแลกเปลี่ยนวันนี้' },
    { icon: '📦', label: 'สินเชื่อส่งออก', query: 'สินเชื่อส่งออก' },
    { icon: '📝', label: 'Letter of Credit', query: 'บริการ L/C' },
  ];

  return (
    <>
      {/* Chat Button */}
      <button
        onClick={toggleChat}
        className={`fixed bottom-6 right-6 w-16 h-16 bg-primary-600 text-white rounded-full shadow-lg hover:bg-primary-700 transition-all z-50 flex items-center justify-center ${isOpen ? 'scale-90' : 'hover:scale-110'}`}
      >
        {isOpen ? (
          <span className="text-2xl">✕</span>
        ) : (
          <>
            <span className="text-2xl">💬</span>
            {unreadCount > 0 && (
              <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs w-5 h-5 rounded-full flex items-center justify-center animate-pulse">
                {unreadCount}
              </span>
            )}
          </>
        )}
      </button>

      {/* Chat Window */}
      {isOpen && (
        <div className="fixed bottom-24 right-6 w-96 h-[500px] bg-white rounded-2xl shadow-2xl z-50 flex flex-col overflow-hidden animate-fadeIn">
          {/* Header */}
          <div className="bg-gradient-to-r from-primary-600 to-primary-700 text-white p-4">
            <div className="flex justify-between items-center">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-white/20 rounded-full flex items-center justify-center text-xl">
                  🤖
                </div>
                <div>
                  <h3 className="font-semibold">EXIM Bank AI</h3>
                  <span className="text-xs text-primary-200 flex items-center gap-1">
                    <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></span>
                    ออนไลน์
                  </span>
                </div>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={clearChat}
                  className="w-8 h-8 rounded-full hover:bg-white/20 flex items-center justify-center transition-colors"
                  title="ล้างการสนทนา"
                >
                  🗑️
                </button>
                <button
                  onClick={toggleChat}
                  className="w-8 h-8 rounded-full hover:bg-white/20 flex items-center justify-center transition-colors"
                  title="ปิด"
                >
                  ✕
                </button>
              </div>
            </div>
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-gray-50">
            {messages.length === 0 ? (
              <div className="text-center py-6">
                <div className="w-16 h-16 mx-auto bg-primary-100 rounded-full flex items-center justify-center text-3xl mb-4">
                  🤖
                </div>
                <h4 className="font-semibold text-gray-800 mb-2">สวัสดีค่ะ!</h4>
                <p className="text-gray-600 mb-1">ยินดีต้อนรับสู่ EXIM Bank AI Assistant</p>
                <p className="text-sm text-gray-500 mb-6">สอบถามข้อมูลบริการธนาคาร หรือต้องการความช่วยเหลือ พิมพ์ข้อความได้เลยค่ะ</p>
                
                {/* Quick Actions */}
                <div className="space-y-2">
                  {quickActions.map((action, index) => (
                    <button
                      key={index}
                      onClick={() => sendQuickMessage(action.query)}
                      className="block w-full text-left px-4 py-3 bg-white rounded-lg text-sm hover:bg-primary-50 hover:text-primary-700 transition-colors border border-gray-200"
                    >
                      <span className="mr-2">{action.icon}</span>
                      {action.label}
                    </button>
                  ))}
                </div>
              </div>
            ) : (
              messages.map((msg, index) => (
                <div
                  key={index}
                  className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  {msg.role === 'assistant' && (
                    <div className="w-8 h-8 bg-primary-100 rounded-full flex items-center justify-center text-sm mr-2 flex-shrink-0">
                      🤖
                    </div>
                  )}
                  <div
                    className={`max-w-[80%] p-3 rounded-2xl ${
                      msg.role === 'user'
                        ? 'bg-primary-600 text-white rounded-br-none'
                        : 'bg-white text-gray-800 rounded-bl-none shadow-md'
                    }`}
                  >
                    <div className="whitespace-pre-wrap text-sm" dangerouslySetInnerHTML={{ __html: msg.content }} />
                    <p
                      className={`text-xs mt-1 ${
                        msg.role === 'user' ? 'text-primary-200' : 'text-gray-400'
                      }`}
                    >
                      {msg.timestamp.toLocaleTimeString('th-TH', {
                        hour: '2-digit',
                        minute: '2-digit',
                      })}
                    </p>
                  </div>
                </div>
              ))
            )}
            
            {/* Loading */}
            {isLoading && (
              <div className="flex justify-start">
                <div className="w-8 h-8 bg-primary-100 rounded-full flex items-center justify-center text-sm mr-2 flex-shrink-0">
                  🤖
                </div>
                <div className="bg-white p-4 rounded-2xl rounded-bl-none shadow-md">
                  <div className="flex gap-1">
                    <span className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></span>
                    <span className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></span>
                    <span className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></span>
                  </div>
                </div>
              </div>
            )}
            
            <div ref={messagesEndRef} />
          </div>

          {/* Input */}
          <div className="p-4 bg-white border-t">
            <div className="flex gap-2">
              <input
                type="text"
                value={userInput}
                onChange={(e) => setUserInput(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder="พิมพ์ข้อความ..."
                className="flex-1 px-4 py-2 border border-gray-300 rounded-full focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                disabled={isLoading}
              />
              <button
                onClick={() => sendMessage()}
                disabled={isLoading || !userInput.trim()}
                className="w-10 h-10 bg-primary-600 text-white rounded-full hover:bg-primary-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors flex items-center justify-center"
              >
                <span className="text-lg">➤</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// Angular_DotNet/ClientApp/src/app/components/chat-widget/chat-widget.component.ts
import { Component, OnDestroy, ChangeDetectionStrategy, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, takeUntil, finalize } from 'rxjs';
import { ChatService, NotificationService } from '../../core/services';
import { ChatMessage } from '../../core/models';

/**
 * Floating chat widget component for quick AI interactions.
 * Uses signals for reactive state management.
 */
@Component({
  selector: 'app-chat-widget',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './chat-widget.component.html',
  styleUrl: './chat-widget.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ChatWidgetComponent implements OnDestroy {
  // Signals for reactive state
  readonly isOpen = signal(false);
  readonly messages = signal<ChatMessage[]>([]);
  readonly userInput = signal('');
  readonly isLoading = signal(false);
  readonly unreadCount = signal(0);

  // Computed values
  readonly hasMessages = computed(() => this.messages().length > 0);
  readonly canSend = computed(() => this.userInput().trim().length > 0 && !this.isLoading());

  // Cleanup subject
  private readonly destroy$ = new Subject<void>();

  constructor(
    private readonly chatService: ChatService,
    private readonly notificationService: NotificationService
  ) {}

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  /**
   * Toggle the chat window visibility
   */
  toggleChat(): void {
    this.isOpen.update(open => !open);
    if (this.isOpen()) {
      this.unreadCount.set(0);
    }
  }

  /**
   * Send a message to the AI assistant
   */
  sendMessage(): void {
    const question = this.userInput().trim();
    if (!question || this.isLoading()) return;

    // Add user message
    this.addMessage({
      role: 'user',
      content: question,
      timestamp: new Date()
    });

    // Clear input and set loading state
    this.userInput.set('');
    this.isLoading.set(true);

    // Send request to API
    this.chatService.ask(question)
      .pipe(
        takeUntil(this.destroy$),
        finalize(() => this.isLoading.set(false))
      )
      .subscribe({
        next: (response) => {
          const content = response.success 
            ? response.answer 
            : `เกิดข้อผิดพลาด: ${response.answer}`;
          
          this.addMessage({
            role: 'assistant',
            content,
            timestamp: new Date()
          });

          // Increment unread count if chat is closed
          if (!this.isOpen()) {
            this.unreadCount.update(count => count + 1);
          }
        },
        error: (err) => {
          const errorMessage = err.error?.answer || err.message || 'เกิดข้อผิดพลาดที่ไม่ทราบสาเหตุ';
          
          this.addMessage({
            role: 'assistant',
            content: `เกิดข้อผิดพลาด: ${errorMessage}`,
            timestamp: new Date()
          });
        }
      });
  }

  /**
   * Handle quick action buttons
   */
  sendQuickMessage(message: string): void {
    this.userInput.set(message);
    this.sendMessage();
  }

  /**
   * Handle keyboard events in the input field
   */
  onKeyPress(event: KeyboardEvent): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.sendMessage();
    }
  }

  /**
   * Clear all chat messages
   */
  clearChat(): void {
    this.messages.set([]);
    this.notificationService.showInfo('ล้างการสนทนาแล้ว');
  }

  /**
   * Update the user input value
   */
  updateUserInput(value: string): void {
    this.userInput.set(value);
  }

  /**
   * Track messages by timestamp for optimization
   */
  trackByTimestamp(_index: number, message: ChatMessage): number {
    return message.timestamp.getTime();
  }

  /**
   * Add a message to the chat history
   */
  private addMessage(message: ChatMessage): void {
    this.messages.update(msgs => [...msgs, message]);
  }
}

<!-- Floating Chat Button -->
<button class="chat-toggle" (click)="toggleChat()" [class.open]="isOpen()">
  @if (isOpen()) {
    <span class="icon close">✕</span>
  } @else {
    <span class="icon chat">💬</span>
    @if (unreadCount() > 0) {
      <span class="badge">{{ unreadCount() }}</span>
    }
  }
</button>

<!-- Chat Window -->
<div class="chat-window" [class.open]="isOpen()">
  <div class="chat-header">
    <div class="header-info">
      <div class="avatar">🏦</div>
      <div class="header-text">
        <h3>EXIM Bank AI</h3>
        <span class="status">
          <span class="status-dot"></span>
          ออนไลน์
        </span>
      </div>
    </div>
    <div class="header-actions">
      <button class="action-btn" (click)="clearChat()" title="ล้างการสนทนา">🗑️</button>
      <button class="action-btn" (click)="toggleChat()" title="ปิด">✕</button>
    </div>
  </div>

  <div class="messages-container">
    @if (!hasMessages()) {
      <div class="welcome-message">
        <div class="welcome-icon">🏦</div>
        <h4>สวัสดีค่ะ!</h4>
        <p>ยินดีต้อนรับสู่ EXIM Bank AI Assistant</p>
        <p class="sub">สอบถามข้อมูลบริการธนาคาร หรือต้องการความช่วยเหลือ พิมพ์ข้อความได้เลยค่ะ</p>
        <div class="quick-actions">
          <button (click)="sendQuickMessage('อัตราแลกเปลี่ยนวันนี้')">💱 อัตราแลกเปลี่ยน</button>
          <button (click)="sendQuickMessage('สินเชื่อส่งออก')">📦 สินเชื่อส่งออก</button>
          <button (click)="sendQuickMessage('บริการ L/C')">📄 Letter of Credit</button>
        </div>
      </div>
    }

    @for (msg of messages(); track trackByTimestamp($index, msg)) {
      <div class="message" [class.user]="msg.role === 'user'" [class.assistant]="msg.role === 'assistant'">
        @if (msg.role === 'assistant') {
          <div class="msg-avatar">🏦</div>
        }
        <div class="msg-content">
          <div class="msg-text" [innerHTML]="msg.content"></div>
          <div class="msg-time">{{ msg.timestamp | date:'HH:mm' }}</div>
        </div>
      </div>
    }

    @if (isLoading()) {
      <div class="message assistant">
        <div class="msg-avatar">🏦</div>
        <div class="msg-content">
          <div class="typing">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      </div>
    }
  </div>

  <div class="input-area">
    <input 
      type="text"
      [ngModel]="userInput()" 
      (ngModelChange)="updateUserInput($event)"
      (keypress)="onKeyPress($event)"
      placeholder="พิมพ์ข้อความ..."
      [disabled]="isLoading()">
    <button class="send-btn" (click)="sendMessage()" [disabled]="!canSend()">
      <span>➤</span>
    </button>
  </div>
</div>
