// Angular_DotNet/ClientApp/src/app/components/search/search.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectionStrategy, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, takeUntil, finalize, debounceTime, distinctUntilChanged } from 'rxjs';
import { SearchService, DocumentService, NotificationService } from '../../core/services';
import { SearchResult, Document } from '../../core/models';

type TabType = 'search' | 'documents';

/**
 * Search component for searching and managing documents.
 * Uses signals for reactive state management with autocomplete support.
 */
@Component({
  selector: 'app-search',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './search.component.html',
  styleUrl: './search.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SearchComponent implements OnInit, OnDestroy {
  // Signals for reactive state
  readonly searchQuery = signal('');
  readonly searchResults = signal<SearchResult[]>([]);
  readonly allDocuments = signal<Document[]>([]);
  readonly isSearching = signal(false);
  readonly isLoadingDocs = signal(false);
  readonly errorMessage = signal('');
  readonly activeTab = signal<TabType>('search');
  
  // Autocomplete signals
  readonly showSuggestions = signal(false);
  readonly filteredSuggestions = computed(() => {
    const query = this.searchQuery().toLowerCase().trim();
    if (!query || query.length < 1) return [];
    
    return this.allDocuments()
      .filter(doc => 
        doc.title.toLowerCase().includes(query) || 
        doc.fileName.toLowerCase().includes(query)
      )
      .slice(0, 5); // Limit to 5 suggestions
  });

  // Computed values
  readonly hasSearchResults = computed(() => this.searchResults().length > 0);
  readonly hasDocuments = computed(() => this.allDocuments().length > 0);
  readonly canSearch = computed(() => this.searchQuery().trim().length > 0 && !this.isSearching());
  readonly searchResultsCount = computed(() => this.searchResults().length);
  readonly documentsCount = computed(() => this.allDocuments().length);

  // Cleanup subject
  private readonly destroy$ = new Subject<void>();
  private suggestionTimeout: ReturnType<typeof setTimeout> | null = null;

  constructor(
    private readonly searchService: SearchService,
    private readonly documentService: DocumentService,
    private readonly notificationService: NotificationService
  ) {}

  ngOnInit(): void {
    this.loadDocuments();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  /**
   * Switch between search and documents tabs
   */
  switchTab(tab: TabType): void {
    this.activeTab.set(tab);
    if (tab === 'documents') {
      this.loadDocuments();
    }
  }

  /**
   * Execute search query
   */
  search(): void {
    const query = this.searchQuery().trim();
    if (!query) return;

    this.isSearching.set(true);
    this.errorMessage.set('');
    this.searchResults.set([]);

    this.searchService.search(query)
      .pipe(
        takeUntil(this.destroy$),
        finalize(() => this.isSearching.set(false))
      )
      .subscribe({
        next: (response) => {
          if (response.success) {
            this.searchResults.set(response.results);
            if (response.results.length === 0) {
              this.notificationService.showInfo('ไม่พบผลลัพธ์', `ไม่พบเอกสารที่ตรงกับ "${query}"`);
            }
          } else {
            this.errorMessage.set(response.error || 'เกิดข้อผิดพลาดในการค้นหา');
          }
        },
        error: (err) => {
          this.errorMessage.set(err.error?.error || err.message || 'เกิดข้อผิดพลาดในการค้นหา');
          this.notificationService.showError('ค้นหาล้มเหลว', this.errorMessage());
        }
      });
  }

  /**
   * Load all documents
   */
  loadDocuments(): void {
    this.isLoadingDocs.set(true);
    
    this.documentService.getAllDocuments()
      .pipe(
        takeUntil(this.destroy$),
        finalize(() => this.isLoadingDocs.set(false))
      )
      .subscribe({
        next: (response) => {
          if (response.success) {
            this.allDocuments.set(response.documents);
          }
        },
        error: (err) => {
          console.error('Error loading documents:', err);
          this.notificationService.showError('โหลดเอกสารล้มเหลว');
        }
      });
  }

  /**
   * Delete a document
   */
  deleteDocument(id: string): void {
    if (!confirm('คุณต้องการลบเอกสารนี้หรือไม่?')) return;

    this.documentService.deleteDocument(id)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response) => {
          if (response.success) {
            this.allDocuments.update(docs => docs.filter(d => d.id !== id));
            this.notificationService.showSuccess('ลบเอกสารสำเร็จ');
          }
        },
        error: (err) => {
          console.error('Error deleting document:', err);
          this.notificationService.showError('ลบเอกสารล้มเหลว');
        }
      });
  }

  /**
   * Handle keyboard events in search input
   */
  onKeyPress(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.showSuggestions.set(false);
      this.search();
    }
  }

  /**
   * Handle search input with autocomplete
   */
  onSearchInput(value: string): void {
    this.searchQuery.set(value);
    if (value.trim().length > 0) {
      this.showSuggestions.set(true);
    } else {
      this.showSuggestions.set(false);
    }
  }

  /**
   * Select a suggestion from dropdown
   */
  selectSuggestion(doc: Document): void {
    this.searchQuery.set(doc.title);
    this.showSuggestions.set(false);
    this.search();
  }

  /**
   * Hide suggestions with delay (for click handling)
   */
  hideSuggestionsDelayed(): void {
    this.suggestionTimeout = setTimeout(() => {
      this.showSuggestions.set(false);
    }, 200);
  }

  /**
   * Update search query value
   */
  updateSearchQuery(value: string): void {
    this.searchQuery.set(value);
  }

  /**
   * Track search results by id
   */
  trackByResultId(_index: number, result: SearchResult): string {
    return result.id;
  }

  /**
   * Track documents by id
   */
  trackByDocId(_index: number, doc: Document): string {
    return doc.id;
  }
}

<div class="search-container">
  <div class="tabs">
    <button 
      [class.active]="activeTab() === 'search'" 
      (click)="switchTab('search')">
      ค้นหาเอกสาร
    </button>
    <button 
      [class.active]="activeTab() === 'documents'" 
      (click)="switchTab('documents')">
      เอกสารทั้งหมด
    </button>
  </div>

  @if (activeTab() === 'search') {
    <div class="search-section">
      <div class="search-box-wrapper">
        <div class="search-box">
          <input 
            type="text" 
            [ngModel]="searchQuery()" 
            (ngModelChange)="onSearchInput($event)"
            (keypress)="onKeyPress($event)"
            (focus)="showSuggestions.set(true)"
            (blur)="hideSuggestionsDelayed()"
            placeholder="พิมพ์คำค้นหาเอกสาร..."
            [disabled]="isSearching()">
          <button (click)="search()" [disabled]="!canSearch()">
            @if (isSearching()) {
              <span class="spinner"></span>
            } @else {
              🔍
            }
          </button>
        </div>

        <!-- Autocomplete Suggestions -->
        @if (showSuggestions() && filteredSuggestions().length > 0) {
          <div class="suggestions-dropdown">
            @for (suggestion of filteredSuggestions(); track suggestion.id) {
              <div class="suggestion-item" (mousedown)="selectSuggestion(suggestion)">
                <span class="suggestion-icon">📄</span>
                <div class="suggestion-content">
                  <span class="suggestion-title">{{ suggestion.title }}</span>
                  <span class="suggestion-filename">{{ suggestion.fileName }}</span>
                </div>
              </div>
            }
          </div>
        }
      </div>

      @if (errorMessage()) {
        <div class="error-message">
          {{ errorMessage() }}
        </div>
      }

      @if (hasSearchResults()) {
        <div class="results">
          <h3>ผลการค้นหา ({{ searchResultsCount() }} รายการ)</h3>
          @for (result of searchResults(); track trackByResultId($index, result)) {
            <div class="result-item">
              <div class="result-header">
                <span class="title">{{ result.title }}</span>
                <span class="score">Score: {{ result.score.toFixed(2) }}</span>
              </div>
              <p class="snippet">{{ result.snippet }}</p>
            </div>
          }
        </div>
      } @else if (!isSearching() && searchQuery() && !errorMessage()) {
        <div class="no-results">
          <span class="icon">📭</span>
          <p>ไม่พบผลลัพธ์สำหรับ "{{ searchQuery() }}"</p>
        </div>
      }
    </div>
  }

  @if (activeTab() === 'documents') {
    <div class="documents-section">
      @if (isLoadingDocs()) {
        <div class="loading">
          <span class="spinner large"></span>
          <p>กำลังโหลดเอกสาร...</p>
        </div>
      } @else if (hasDocuments()) {
        <div class="documents-list">
          <h3>เอกสารทั้งหมด ({{ documentsCount() }} รายการ)</h3>
          <table>
            <thead>
              <tr>
                <th>ชื่อเรื่อง</th>
                <th>ชื่อไฟล์</th>
                <th>การดำเนินการ</th>
              </tr>
            </thead>
            <tbody>
              @for (doc of allDocuments(); track trackByDocId($index, doc)) {
                <tr>
                  <td>{{ doc.title }}</td>
                  <td>{{ doc.fileName }}</td>
                  <td>
                    <button class="delete-btn" (click)="deleteDocument(doc.id)">ลบ</button>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      } @else {
        <div class="empty-state">
          <span class="icon">📄</span>
          <p>ยังไม่มีเอกสาร</p>
          <small>อัพโหลดเอกสารเพื่อเริ่มต้นใช้งาน</small>
        </div>
      }
    </div>
  }
</div>

// NodeJs_NextJs/src/app/search/page.tsx
'use client';

import { useState, useCallback, useEffect, useMemo } from 'react';
import { SearchResult, Document } from '@/types';

type TabType = 'search' | 'documents';

// Default search suggestions
const DEFAULT_SUGGESTIONS = [
  'อัตราแลกเปลี่ยน',
  'สินเชื่อส่งออก',
  'Letter of Credit',
  'Forward Contract',
  'ประกันการส่งออก',
  'บริการโอนเงิน',
  'เอกสารการค้า',
  'Trust Receipt',
];

export default function SearchPage() {
  const [activeTab, setActiveTab] = useState<TabType>('search');
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<SearchResult[]>([]);
  const [allDocuments, setAllDocuments] = useState<Document[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [isLoadingDocs, setIsLoadingDocs] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [showSuggestions, setShowSuggestions] = useState(false);

  // Filter suggestions based on search query
  const filteredSuggestions = useMemo(() => {
    if (!searchQuery.trim()) return DEFAULT_SUGGESTIONS;
    return DEFAULT_SUGGESTIONS.filter(s => 
      s.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [searchQuery]);

  const loadDocuments = useCallback(async () => {
    setIsLoadingDocs(true);
    try {
      const response = await fetch('/api/upload');
      const data = await response.json();
      if (data.success) {
        setAllDocuments(data.documents);
      }
    } catch (err) {
      console.error('Error loading documents:', err);
    } finally {
      setIsLoadingDocs(false);
    }
  }, []);

  useEffect(() => {
    loadDocuments();
  }, [loadDocuments]);

  const handleSearch = async (query?: string) => {
    const searchTerm = (query || searchQuery).trim();
    if (!searchTerm) return;

    setSearchQuery(searchTerm);
    setShowSuggestions(false);
    setIsSearching(true);
    setErrorMessage('');
    setSearchResults([]);

    try {
      const response = await fetch(`/api/search?q=${encodeURIComponent(searchTerm)}`);
      const data = await response.json();

      if (data.success) {
        setSearchResults(data.results);
        if (data.results.length === 0) {
          setErrorMessage(`ไม่พบเอกสารที่ตรงกับ "${searchTerm}"`);
        }
      } else {
        setErrorMessage(data.error || 'เกิดข้อผิดพลาดในการค้นหา');
      }
    } catch (err) {
      setErrorMessage('เกิดข้อผิดพลาดในการค้นหา');
    } finally {
      setIsSearching(false);
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    setSearchQuery(suggestion);
    setShowSuggestions(false);
    handleSearch(suggestion);
  };

  const handleDeleteDocument = async (id: string) => {
    if (!confirm('คุณต้องการลบเอกสารนี้หรือไม่?')) return;

    try {
      const response = await fetch(`/api/upload/documents/${id}`, {
        method: 'DELETE',
      });
      const data = await response.json();

      if (data.success) {
        setAllDocuments(allDocuments.filter(d => d.id !== id));
      }
    } catch (err) {
      console.error('Error deleting document:', err);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleSearch();
    }
  };

  const formatFileSize = (bytes: number) => {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 animate-fadeIn">
      {/* Header */}
      <div className="text-center">
        <h1 className="text-3xl font-bold text-gray-800 mb-2">🔍 ค้นหาเอกสาร</h1>
        <p className="text-gray-600">ค้นหาและจัดการเอกสารในระบบ</p>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-gray-200">
        <button
          onClick={() => setActiveTab('search')}
          className={`px-6 py-3 font-medium transition-colors ${
            activeTab === 'search'
              ? 'text-primary-600 border-b-2 border-primary-600'
              : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          🔍 ค้นหา
        </button>
        <button
          onClick={() => {
            setActiveTab('documents');
            loadDocuments();
          }}
          className={`px-6 py-3 font-medium transition-colors ${
            activeTab === 'documents'
              ? 'text-primary-600 border-b-2 border-primary-600'
              : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          📚 เอกสารทั้งหมด ({allDocuments.length})
        </button>
      </div>

      {/* Search Tab */}
      {activeTab === 'search' && (
        <div className="space-y-6">
          {/* Search Input with Suggestions */}
          <div className="card">
            <div className="relative">
              <div className="flex gap-3">
                <div className="relative flex-1">
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    onFocus={() => setShowSuggestions(true)}
                    onBlur={() => setTimeout(() => setShowSuggestions(false), 200)}
                    onKeyPress={handleKeyPress}
                    placeholder="พิมพ์คำค้นหา..."
                    className="input w-full"
                  />
                  
                  {/* Autocomplete Suggestions Dropdown */}
                  {showSuggestions && filteredSuggestions.length > 0 && (
                    <div className="absolute top-full left-0 right-0 mt-1 bg-white border border-gray-200 rounded-lg shadow-lg z-50 max-h-60 overflow-y-auto">
                      <div className="p-2 text-xs text-gray-500 border-b">💡 คำแนะนำการค้นหา</div>
                      {filteredSuggestions.map((suggestion, index) => (
                        <button
                          key={index}
                          onMouseDown={() => handleSuggestionClick(suggestion)}
                          className="w-full text-left px-4 py-2 hover:bg-primary-50 hover:text-primary-700 transition-colors flex items-center gap-2"
                        >
                          <span className="text-gray-400">🔍</span>
                          {suggestion}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
                <button
                  onClick={() => handleSearch()}
                  disabled={isSearching || !searchQuery.trim()}
                  className="btn btn-primary px-6"
                >
                  {isSearching ? (
                    <>
                      <span className="spinner w-5 h-5 mr-2"></span>
                      กำลังค้นหา...
                    </>
                  ) : (
                    '🔍 ค้นหา'
                  )}
                </button>
              </div>
            </div>
            
            {/* Quick Search Tags */}
            <div className="mt-4 flex flex-wrap gap-2">
              <span className="text-sm text-gray-500">ค้นหาด่วน:</span>
              {DEFAULT_SUGGESTIONS.slice(0, 5).map((tag, index) => (
                <button
                  key={index}
                  onClick={() => handleSuggestionClick(tag)}
                  className="px-3 py-1 bg-gray-100 hover:bg-primary-100 hover:text-primary-700 text-sm rounded-full transition-colors"
                >
                  {tag}
                </button>
              ))}
            </div>
          </div>

          {/* Error Message */}
          {errorMessage && (
            <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg text-yellow-800">
              ⚠️ {errorMessage}
            </div>
          )}

          {/* Search Results */}
          {searchResults.length > 0 && (
            <div className="card">
              <h3 className="font-semibold mb-4">
                ผลการค้นหา ({searchResults.length} รายการ)
              </h3>
              <div className="space-y-4">
                {searchResults.map((result) => (
                  <div
                    key={result.id}
                    className="p-4 border rounded-lg hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex justify-between items-start">
                      <div className="flex-1">
                        <h4 className="font-semibold text-gray-800 mb-1">
                          📄 {result.title}
                        </h4>
                        <p className="text-sm text-gray-600 mb-2">{result.snippet}</p>
                        <div className="flex items-center gap-4 text-xs text-gray-400">
                          <span className="px-2 py-1 bg-green-100 text-green-700 rounded-full">
                            คะแนน: {result.score.toFixed(1)}%
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Empty State */}
          {!isSearching && searchResults.length === 0 && !errorMessage && (
            <div className="card text-center py-12">
              <div className="text-6xl mb-4">🔎</div>
              <h3 className="text-xl font-semibold text-gray-700 mb-2">ค้นหาเอกสาร</h3>
              <p className="text-gray-500">พิมพ์คำค้นหาเพื่อค้นหาเอกสารในระบบ</p>
            </div>
          )}
        </div>
      )}

      {/* Documents Tab */}
      {activeTab === 'documents' && (
        <div className="space-y-6">
          {isLoadingDocs ? (
            <div className="card text-center py-12">
              <div className="spinner w-12 h-12 mx-auto mb-4"></div>
              <p className="text-gray-500">กำลังโหลดเอกสาร...</p>
            </div>
          ) : allDocuments.length > 0 ? (
            <div className="card">
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead>
                    <tr>
                      <th className="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        เอกสาร
                      </th>
                      <th className="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        ขนาด
                      </th>
                      <th className="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        วันที่อัพโหลด
                      </th>
                      <th className="px-6 py-3 bg-gray-50 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                        การดำเนินการ
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {allDocuments.map((doc) => (
                      <tr key={doc.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="flex items-center">
                            <span className="text-2xl mr-3">📄</span>
                            <div>
                              <p className="font-medium text-gray-900">{doc.title}</p>
                              <p className="text-sm text-gray-500">{doc.fileName}</p>
                            </div>
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {formatFileSize(doc.size)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {new Date(doc.uploadedAt).toLocaleString('th-TH')}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-right">
                          <button
                            onClick={() => handleDeleteDocument(doc.id)}
                            className="text-red-600 hover:text-red-800 font-medium text-sm"
                          >
                            🗑️ ลบ
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          ) : (
            <div className="card text-center py-12">
              <div className="text-6xl mb-4">📭</div>
              <h3 className="text-xl font-semibold text-gray-700 mb-2">ยังไม่มีเอกสาร</h3>
              <p className="text-gray-500">ไปที่หน้าอัพโหลดเพื่อเพิ่มเอกสารใหม่</p>
              <a href="/upload" className="btn btn-primary mt-4 inline-block">
                📤 อัพโหลดเอกสาร
              </a>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
